### ISSUE TITLE
fatal error: shm_msgs/msg/image.hpp: No such file or directory

### ISSUE THREAD

**Issue by rawnam** [ZhenshengLee/ros2_v4l2_camera#2]
ros2_v4l2_camera/include/v4l2_camera/v4l2_camera_device.hpp:20:10: fatal error: shm_msgs/msg/image.hpp: No such file or directory
   20 | #include "shm_msgs/msg/image.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ZhenshengLee** [comment]
compile it with shm_msgs, which is https://github.com/ZhenshengLee/ros2_shm_msgs

**Comment by rawnam** [comment]
I am doing that and the shm_msgs header files are available in the install folder in the workspace but still it's giving this error. Anything missing in the CMakeLists to find the header files?

**Comment by ZhenshengLee** [comment]
> I am doing that and the shm_msgs header files are available in the install folder in the workspace but still it's giving this error. Anything missing in the CMakeLists to find the header files?

currently I cannot reproduce your behavior, can you follow what I said here https://github.com/ZhenshengLee/ros2_v4l2_camera/issues/1#issuecomment-1340273246 so I can follow you and make the repo get compiled in Humble?

Thanks.

**Comment by ZhenshengLee** [comment]
https://github.com/ZhenshengLee/ros2_shm_msgs/commit/42fde5f188dc5a55be54718cbb601539d2823815 and https://github.com/ZhenshengLee/ros2_v4l2_camera/commit/156d54ed3eeee45409b5e81f615dc40cdb60dd56 should fix the issue and get compiled.

please use the outdoor/humble branch. @arukan404 

Close the issue if it's been resolved.

**Comment by rawnam** [comment]
I pulled the latest commits on both shm_msgs and v4l2_camera... Still facing the same issue
ros2_v4l2_camera/include/v4l2_camera/v4l2_camera_device.hpp:20:10: fatal error: shm_msgs/msg/image.hpp: No such file or directory
20 | #include "shm_msgs/msg/image.hpp"

**Comment by ZhenshengLee** [comment]
> I pulled the latest commits on both shm_msgs and v4l2_camera... Still facing the same issue

Don't pull, clone a new workspace, because I've forced push to the repo.
And choose the right branch: humble

**Comment by rawnam** [comment]
Even cloning a new workspace is still giving the same error.

**Comment by rawnam** [comment]
Solved, Created a Pull Request as well 
https://github.com/ZhenshengLee/ros2_shm_msgs/pull/26
